name: event_heart_app
description: App made with Flutter, based in a design about events application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/launcher/ic_launcher.png
  image_path_android: assets/launcher/ic_launcher.png
  adaptive_icon_background: assets/launcher/ic_launcher.png
  adaptive_icon_foreground: assets/launcher/ic_launcher.png

flutter:

  uses-material-design: true

  assets:
    - assets/launcher/
    - assets/images/
    - assets/images/data/

  fonts:
    - family: Atone
      fonts:
        - asset: assets/fonts/Atone.otf
    - family: Dirty Headline
      fonts:
        - asset: assets/fonts/DirtyHeadline.ttf
